### ISSUE TITLE
custom script with setuid do not start

### ISSUE THREAD

**Issue by Miky028** [glftpd/glftpd#49]
OS: FreeBSD 12.1-RELEASE-p10 in jail
glFTPd v2.11 BETA3 (x64) static & full dynamic
glFTPd v2.10a (x64) static

When I try to run custom script (foo-pre) without setuid bit, it runs without problem except with message to set setuid bit.
When I set setuid bit and run 'site pre' it only returns '200 Command Successful.' and nothing happened.
When I run shell custom script '/bin/foo-pre $1 $2' output is '200- Abort trap'.

I tried chrooted environment and foo-pre with setuid run without a problem.

Any advice please?
THX

**Comment by teqnodude** [comment]
"When I set setuid bit and run 'site pre' it only returns '200 Command Successful.' and nothing happened."

That to me indicate that the execution of the foo-pre binary works as it should so the problem isn't with glftpd, the problem is more likely to do with foo-pre binary or/and foo-pre settings. My suggestion is that you run with this foo-pre `git clone https://github.com/silv3rr/foo-tools` and with this checkout version `git checkout cdb77c1`.

I have tried newer versions of foo-pre myself that didn't work that well which is why I recommend that specific checkout and version.

**Comment by Miky028** [comment]
Thanks for replay, but...
Same thing happened.
Glftpd output nothing when error occurs. So I think that sh 'wrapper' came with 'Abort trap'. So that mean something?
Maybe it's FreeBSD related? Or jail? On Linux were foo-pre working without any problems even with setuid.

**Comment by Miky028** [comment]
Pre with setuid is working right now. Idk what helped exactly. My bet is recompiling /glftpd/bin/sources.
